web:
  container_name: php7.2.24_apache_oci8-QAStatus
  build: .
  ports:
    - "80:80"
  volumes:
    - ./src:/var/www/html/
    - ./conf/apache:/etc/apache2/sites-enabled/
    - ./conf/php:/usr/local/etc/php/

